version = 0.1
[default.deploy.parameters]
stack_name = "EKS-pod-logs-to-CloudTrailLake"
resolve_s3 = true
s3_prefix = "EKS-pod-logs-to-CloudTrailLake"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "LogImportFrequency=\"rate(1 day)\" EKSPodNames=\"UI,fluent\" EKSS3LogLocation=\"eks-log-fluent-bit-143466417256\""
image_repositories = []
